SmartThingsCommunity/smartapp-sdk-nodejs

.github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/PR_CHECKLIST_TEMPLATE.md

Bug report, feature request, and pull request.
**edit:** I added these through the GitHub UI and it was a strange procedure which created this branch for me. I cannot test it until it's in the repo so there may be additional PRs.

Add issue templates

---

package.json

Set the minimum node engine to 8.9.4

---

README.md

Update readme.md examples

---

.circleci/config.yml
.gitignore
README.md
package-lock.json
package.json

Include CI, automatically running the linter, tests and uploading code coverage info to codecov.io.

[PI-359] Set up CI.

---

README.md

Fixes #15 
Put back accidentally removed quotes.
---

Fix quotes issue in readme.

---

README.md

Add CircleCI and Codecov badges.

Add CircleCI and Codecov badges.

---

lib/smart-app.js
test/smartapp-page-spec.js
test/smartapp-spec.js

Fix #10
Fix uninstalled() handler not receiving a callback (it was attached to installedHandler)
Add spec to test handlers
Add assertions to smartapp-page-spec
Improve test coverage

Fix uninstalled() assigning to wrong handler

---

lib/smart-app.js

Add method to set OAuth handler and fixed incorrect callback data property name.

Add ability to set OAuth handler

---

lib/platform/installedapps.js

Typo in installedAppId

---

lib/platform/scenes.js
lib/platform/subscriptions.js

Fixes #31
Note... we have no unit testing for API calls yet.

Fix request function call

---

.circleci/config.yml

Publish artifacts from this repository using semantic-release.

fix: add checkout to publish step

---

lib/platform/apps.js

cc @jimmyjames @rossiam @erodewald

Fix: Added delete api request method

---

lib/pages/paragraph-setting.js

Closes #56 
Fix usage of this over super

Add ability to set description on paragraph

---

README.md
lib/platform/apps.js
lib/platform/client-error.js
lib/platform/client.js
lib/platform/deviceprofiles.js
lib/platform/devices.js
lib/platform/installedapps.js
lib/platform/locations.js
lib/platform/modes.js
lib/platform/scenes.js
lib/platform/schedules.js
lib/platform/subscriptions.js
lib/smart-app.js
lib/util/endpoint-context.js
lib/util/log.js
package.json

Updated error logging to properly catch exceptions so that ST API errors no longer result in unhandled promise rejections, i.e. error like:
```
(node:20760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Also cleaned up a bunch of coding style changed and updated the example to reflect that handlers calling the API should either wait for API calls to finish or return the promise. Also updated the …

Error handling and code style fixes

---

.circleci/config.yml
config/release.config.js
package-lock.json
package.json

This will need to be tested by merging and publishing. 
```
Add semantic-release config
ci: add/update dependencies 
Update package-lock
Add xo rule for no-template-curly-in-string
```

fix: semantic-release update package.json

---

.circleci/config.yml

fix: fix publish ci script

---

.github/PULL_REQUEST_TEMPLATE.md

minor doc updates

---

lib/smart-app.js

- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the **[CONTRIBUTING](/CONTRIBUTING.md)** document
- [ x] My code follows the code style of this project (hint: install an [xo editor plugin](https://github.com/xojs/xo#editor-plugins))
- [x ] Any required documentation has been added

Fix: Fix broken Ping lifecycle authorization due to Issue-77 addition

---

lib/smart-app.js
lib/util/log.js
package-lock.json
package.json
test/unit/log-spec.js

Closes #84 
Fixed cases where the logger configuration was not respected, sending them into a blackhole. 
Includes some JsDoc documentation improvements.

fix(logging): logger configuration

---

lib/util/endpoint-context.js
package-lock.json
package.json
test/unit/endpoint-context-spec.js

Closes #50  
* Fix npe-prone code in `configDateValue()`
* Add jsdocs to config* functions

fix: config retrieval inconsistencies

---

doc/platform.md
lib/platform/devices.js
package-lock.json

Change to accept list of commands in a single device request

fix: Accept lists of device commands

---

lib/util/log.js

fix: Output stack trace for uncaught exceptions in handler

---

lib/pages/section.js
lib/platform/devices.js
test/unit/locales/fr.json
test/unit/pagebuilder-i18n-spec.js

fix: bugs in devices by capability query and section name localization

---

doc/platform.md
lib/api.js
lib/platform/rooms.js

Closes #97 
Added support for rooms API calls

fix: Added rooms API

---

.github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md
.github/ISSUE_TEMPLATE/question-template.md

Note: when making template changes through GitHub, it doesn't use my fork. We can delete this branch after it's merged in, though.

Update issue templates

---

lib/api.js
lib/platform/notifications.js
lib/smart-app.js
test/unit/util/endpoint-context-spec.js

Notifications api

---

lib/util/smart-app-context.js

fix: hardened acquisition of language in smart-app-context

---

lib/pages/decimal-setting.js

feat: Change to be able to set localized postMessage in decimal-setting

---

lib/smart-app.js
package-lock.json
test/unit/event-type-handler-spec.js
test/unit/events/device-event-spec.js

Change to pass event time to handlers

feat: Pass event time to handlers

---

lib/pages/page-setting.js
lib/pages/text-setting.js
lib/platform/schedules.js
package-lock.json
package.json

Bug fixes for two issues.
https://github.com/SmartThingsCommunity/smartapp-sdk-nodejs/issues/122
https://github.com/SmartThingsCommunity/smartapp-sdk-nodejs/issues/123
Improvement to allow the localization of `textSetting`
https://github.com/SmartThingsCommunity/smartapp-sdk-nodejs/issues/125

Small bug fixes and localization of textSetting

---

lib/pages/text-setting.js

fix: reverted text-setting change at #127 as #131 merged

---

doc/platform.md
lib/api.js
lib/platform/rules.js

Added support for calling the rules API.

feat: Added support for rules API

---

.github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md
.github/ISSUE_TEMPLATE/question-template.md

Remove myself from issue template assignees.

Remove assignee

---

lib/smart-app.js
lib/util/authorizer.js
package-lock.json
package.json

Updated core-sdk version to add location service endpoint and fix bugs in device creation and events generation

feat: Updated core SDK for service support and bug fixes

---

package.json

Update core SDK major version to pull in subscriptions create fix

fix: Updated core SDK to fix subscription create bug

---

.circleci/config.yml
config/release.config.js
package-lock.json
package.json

* pin version of ci runner to 10.x latest
* upgrade `semantic-release` and remove redundant plugin installs

ci: enable github releases

---

package-lock.json

* replace dependency in package-lock that is automatically included by semantic-release

CI: add commit-analyzer to package-lock

---

docs/modules/_i18n_d_.md
docs/modules/_lifecycle_events_d_.md
docs/modules/_pages_enum_setting_d_.md
docs/modules/_smart_app_d_.md
package-lock.json
package.json

Added missing module documents and updated the version of the core SDK used.

fix: Added modules docs

---

package-lock.json
package.json

Updated axios and core-sdk versions to address vulnerabilities

fix: Updated axios and core-sdk versions

---

README.md

docs(README): link to examples topic

---

package-lock.json
package.json

fix(deps): npm audit

---

.vscode/settings.json
docs/classes/_pages_section_d_.section.md
docs/classes/_smart_app_d_.smartapp.md
docs/index.md
docs/interfaces/_smart_app_d_.smartappoptions.md
lib/pages/section.d.ts
lib/pages/section.js
lib/smart-app.d.ts
lib/smart-app.js
lib/util/initialization.d.ts
package-lock.json
scripts/docgen-post-process.js

This will allow projects that enable [noImplicitAny](https://www.typescriptlang.org/tsconfig#noImplicitAny) to successfully compile.
* fix #187
* fix #188 
* npm audit (dev)

fix(Initialization): add return type annotations

---

jest.config.js
lib/smart-app.js
package-lock.json
package.json
test/data/lifecycles.js
test/unit/lifecycles/installation-lifecycle-spec.js

fix: await async updated handlers during install

---

index.js
lib/pages/page.d.ts
package-lock.json
package.json

Export Page class to support unit testing of SmartApps

feat: Exported Page class to support unit testing of SmartApps

---

.github/workflows/ci-cd.yaml
CONTRIBUTING.md
README.md
docs/V2_RELEASE_NOTES.md

use "main" for main branch name

chore: use "main" for main branch name

---

.releaserc.yaml

Add "main" as the release branch

fix: specify main as the semantic release branch

---

CONTRIBUTING.md
README.md
docs/V2_RELEASE_NOTES.md
docs/classes/_smart_app_d_.smartapp.md
docs/classes/smartapp.md
docs/index.md
docs/modules/_lifecycle_events_d_.md
lib/lifecycle-events.d.ts
lib/pages/page.js
lib/smart-app.d.ts

- update links in documentation
- other minor fixes to documentation

docs: update links in documentation

---

CONTRIBUTING.md
LICENSE
NOTICE.txt
README.md

Replace `SmartThings, Inc.` with `Samsung Electronics Co., LTD.`

docs: Update copyright company name

---

docs/interfaces/_util_smart_app_context_d_.smartappcontext.md
lib/pages/email-setting.js
lib/smart-app.js
lib/util/smart-app-context.d.ts
lib/util/smart-app-context.js
package-lock.json
package.json
test/unit/lifecycles/oauth-callback-lifecycle-spec.js
test/unit/smartapp-context-spec.js
test/utilities/context-store.js

Added methods to the context object to get and set properties that are stored in the `state` field of the context record. These methods are useful for storing information associated with each installed app instance, such as third-party API access tokens, without implementing a separate data store.

feat: added methods to store and retrieve state in the context store

---

.github/workflows/ci-cd.yaml

Changed node-version in ci-cd to fix actions error

feat: release of context store methods

---

package-lock.json
package.json

Pull in core-SDK update that decouples axios version.

fix: decouple axios version from core SDK

---

package-lock.json
package.json

Update to the latest core SDK which has a workaround for an [axios issue](https://github.com/axios/axios/issues/6341). Also updated axios version used by this project.

fix: update to core SDK to fix axios issue
