SmartThingsCommunity/smartapp-sdk-nodejs

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
LICENSE
README.md
package.json

- Fix Apache license copyrights
- Move and rename PR template to try to get it to work
- Add CONTRIBUTING.md
- It includes links to open new issues/feature requests, opening new pull requests, etc. 
_Looking for constructive criticism on my copy!_ ✌️

Remove unnecessary space at end of line

---

CODE_OF_CONDUCT.md

Contributor Covenant's code of conduct seems like a good thing to add

Create standardized CODE_OF_CONDUCT.md

---

lib/pages/page.js
lib/smart-app.js
package-lock.json
package.json
test/smartapp-page-spec.js

Change to allow configuration pages to include async function calls so that page content can be dynamically generated from calls to databases or other external data sources.

Added support for async calls in pages to return dynamic content

---

lib/platform/client.js
package-lock.json
package.json

Switched to use of lighter weight native JavaScript promises. Technically this is a breaking change since apps can't use `finally` on promises returned from API calls but it seems unlikely that many users are doing that yet.

feat: Switched to request-promise-native

---

lib/pages/page.js
test/pagebuilder-spec.js

Although this was fixed in PR #48, I introduced a regression in PR #63. 
This closes #47. 
test: ensure unit test for defaultRequired is accurate

fix: set _defaultRequired=false

---

README.md

The docs were missing information about context stores which are vital to out-of-band API calls.

docs: context stores

---

README.md
lib/smart-app.js
package.json

Added default handler for promise rejections that aren't explicitly caught in the SmartApp code, so that useful error messages are logged for things like failed API calls.

fix: Added default unhandled promise rejection handler

---

lib/smart-app.js
package.json
test/smartapp-context-spec.js

Allow API context (access tokens and UUIDs) to be initialized from a simple parameter map as an alternative to using one of the context store modules. This feature is particularly handy for API apps that don't receive lifecycle events and therefore don't benefit from the built-in context persistence behavior. Instead the context is stored any way the app wants and is just passed into the SDK.

fix: Allow context initialization without data store

---

examples/basic/README.md
lib/smart-app.js
lib/util/authorizer.js
test/functional/device-spec.js
test/unit/authorizer-spec.js
test/unit/boolean-setting-spec.js
test/unit/smartapp-context-spec.js

In practice, there were some quirks with using the authorizer class (from both the sdk developer & user perspectives). 
* You can now declare & pass in the options from the root level of the smartapp sdk (`keyHostApi`, `keyCacheTTL`, etc.)
* You can set the `keyHostApi` from the `SmartApp` instance as a chainable function: `keyHostApi('https://key.smartthings.com')`

refactor(authorizer): authorizer polish

---

lib/platform/client.js

The change that added `resolveWithFullResponse: true` to the API client is a breaking change for anyone who is relying on API responses. Instead of returning the JSON body the calls now return an IncomingMessage object with a `body` property. Pushing a hotfix for this issue immediately to unbreak things. We can sort out the functional tests at a later time

fix: removed resolveWithFull response that is a breaking change

---

lib/smart-app.js
lib/util/endpoint-context.js
package-lock.json

CONFIGURATION lifecycle events do not include access tokens, even when an app has already been installed. As a result, it is not possible to use data from the API when rendering configuration pages. This change allows such calls provided the app has defined a context store (and therefore has access
tokens available).
The CONFIGURATION lifecycle event should really return access tokens, at least for installed apps, to allow API calls when rendering configuration pages, but in the meantime this change permits such calls by retrieving the tokens (and location ID, which is also missing) from the context store.

feat: Allow API calls while rendering pages in installed app

---

lib/util/endpoint-context.js

Hotfix to correct bug introduced with config page token change when there is not context store.

fix: Bug in configuration/page retrieveTokens when no ctx store

---

doc/pages.md
lib/smart-app.js
test/unit/smartapp-page-spec.js

Closes #98 
Added option to define a default page handler that is called when the pageId of a configuration/page lifecycle event does not match any of the declared pages. This feature is useful for allowing information to be encoded in pageIds in links, to render pages differently depending on which link was used to display them.

feat: Added default page handler

---

lib/platform/client.js
lib/platform/subscriptions.js
lib/smart-app.js
lib/util/configuration-error.js
package.json
test/unit/event-type-handler-spec.js

Added consistent handling of event type subscriptions. Note that the non-device subscription lifecycle events do not return the subscription name specified in the API call. As a result, there is no basis for dispatching them to the proper named handler. A request has been made to correct that problem in the SmartThings platform, but in the meantime the SDK is modified to accept an optional third argument to `subscribedEventHandler` to specify the type of event being handled. This argument should _not_ be specified for device events, but is required for other event types.
Because the handler name is not returned in the lifecycle event only one handler is possible for each non-device event type. 
Once the platform change has been made this SDK will be updated to use the returned handler …

feat: corrected handlers for non-device event types

---

lib/pages/device-setting.js
package.json
test/unit/pages/boolean-setting-spec.js
test/unit/pages/device-setting-spec.js
test/unit/pages/section-setting-spec.js
test/unit/util/authorizer-spec.js
test/unit/util/configuration-error-spec.js
test/unit/util/endpoint-context-spec.js
test/unit/util/log-spec.js

Ongoing effort toward #100 
`test:` Add nyc low watermark of 40%, high of 95%
`fix:` sub-folder unit tests not running
`fix:` Remove submitOnChange from device-setting (Exists in super)
`fix:` jsdocs in device-setting
`test:` Add configuration-error spec (100% cov)
`test:` Add device-setting-spec (97.5% cov)

test: improve code coverage

---

lib/smart-app.js

This fixes the warnings that are shown when using the `PageCallback` – it erroneously thinks we return an instance of `SmartApp`, but we do not.

fix: pagecallback does not return smartapp instance

---

lib/pages/enum-setting.js
test/unit/locales/fr.json
test/unit/pagebuilder-i18n-spec.js
test/unit/pagebuilder-spec.js

EnumSettings did not support i18n for the following: 
* `options.name`
* `groupedOptions[0].name`
* `groupedOptions[0].options[0].name`

feat: EnumSettings i18n

---

lib/platform/devices.js

Works around a problem in the API where a 404 error is returned from device health status queries for devices that do exist but aren't enrolled in device health. Arguably the API itself should be changed to not do that, but in the meantime, this work-around catches the error and returns an 'UNKNOWN' status for the health of the device.

fix: catch 404 exception from device health for unenrolled devices

---

lib/platform/client.js

Corrects a fairly serious problem where asynchronous API requests (i.e. those not in response to lifecycle events) that encountered errors other than 401 errors would not clear the semaphore used to serialize requests and therefore cause failures of subsequent operations during the same app invocation.
Note that this serialization is done so that concurrent requests that encounter expired auth tokens and trigger an automatic refresh don't step on one another and result in the persistence of an expired refresh token (since we change the refresh token with each request).
This serialization only applies to current API requests made during a single app invocation so it isn't a guarantee against corrupted refresh tokens, but it at least reduces the probability of that occurring. If SmartThings …

fix: release semaphore when sequential api throws non-401 errors

---

lib/platform/client.js
lib/util/smart-app-context.js
package-lock.json

Fixed regression in automatic refreshing of tokens from asynchronous calls to the SmartThings platform (that is, calls not in response to lifecycle events).

fix: Corrected bug in automatic refresh of tokens

---

lib/util/responders.js
package-lock.json

The `enableEventLogging` configuration flag logs lifecycle event requests as well a the responses in the http handler for web-hook apps, but logged only the requests for Lambdas. This change logs both for all handlers.

fix: Log responses as well as events for lambdas as is done for webhooks

---

doc/pages.md
lib/pages/section-setting.js

Previous PR #127 broke the behavior of `textSetting` that was showing nothing properly when the `defaultValue` was not specified. To restore that break, I've added `translatedDefaultValue()` to handle only the case of using locales.

fix: applied translateDefaultValue to SectionSettings

---

lib/platform/client.js
package-lock.json
package.json

Synchronize only refreshing of tokens that that the initial requests when an accessToken expires. This way callbacks can be made in parallel as long as the tokens are valid.

feat: Synchronize only refreshes to preserve multi-threading

---

README.md
lib/smart-app.js
lib/util/log.js
test/unit/events/confirmation-spec.js

Removed auto-confirmation of API Access app target URLs as it is a security issue. Addresses issue #139 
Note that while not a breaking change to the functionality of an API Access app that has already been deployed, this change does affect the app development process in that the app will no longer automatically response to a registration request and therefore the callbacks state will remain PENDING until the user visits the URL printed to the server log.

feat: Removed auto-confirmation for API Access apps

---

lib/smart-app.js
test/unit/events/execute-event-spec.js

Add support for handling execute lifecycle events and returning a response. Addresses issue #121

feat: Return executeData in response to EXECUTE lifecycle event

---

lib/util/smart-app-context.js
test/unit/smartapp-context-spec.js

Construct proper authenticator type depending on whether a context store and mutex for sequential refreshes is defined.
Previously a sequential refresh authenticator was being constructed with potentially undefined values for the context store,
which resulted in unexpected exceptions from the core API in some cases

fix: Construct proper authenticator type

---

lib/smart-app.js

Earlier fix to properly return 422 error for missing event handlers had the side-effect of giving no indication in the server logs
as to which handler was missing. Added logging to provide this indication

fix: log missing event handlers

---

README.md
lib/smart-app.js

Added support for async lambda handlers. Previously you were forced to use the callback function option. Addresses issue #159.

feat: Support async lambda event handlers

---

lib/smart-app.js

Add `await` to context store `put` operations so that failures can be properly handled in the app. Addresses issue #165

fix: Add await to context store put operations

---

docs/classes/_smart_app_d_.smartapp.md
lib/smart-app.d.ts

docs(SmartApp): reference permissions/appId dependency

---

package.json
test/unit/pages/boolean-setting-spec.js
test/unit/pages/device-setting-spec.js
test/unit/pages/enum-setting-spec.js
test/unit/pages/section-setting-spec.js
test/unit/pages/text-setting-spec.js
test/unit/util/authorizer-spec.js
test/unit/util/configuration-error-spec.js
test/unit/util/endpoint-context-spec.js
test/unit/util/log-spec.js

* disable `prefer-arrow-callback` rule for tests, as mocha [discourages arrows](https://mochajs.org/#arrow-functions) in some cases
* add `mocha` env to `xo` config so that linting is aware of `describe` in tests

test(text-setting): add initial coverage

---

lib/smart-app.js
lib/util/smart-app-context.js
test/unit/smartapp-context-spec.js

Pass locale, if set, in the Accept-Language header of API requests

fix: Add Accept-Language to API calls when locale is set

---

docs/classes/_smart_app_d_.smartapp.md
lib/smart-app.d.ts
lib/smart-app.js
lib/util/initialization.d.ts
lib/util/initialization.js
test/unit/smartapp-initialize-spec.js

Added optional handler for CONFIGURATION/INITIALIZE event so that values such as firstPage and permissions can be dynamically set. Addresses issue #176

feat: Added optional handler for CONFIGURATION/INITIALIZE event

---

config/jest.setup.js
jest.config.js
test/unit/smartapp-page-spec.js
test/unit/smartapp-spec.js

* convert some raw `assert` usage to jest `expect`
* add jest setup file to fail on unhandledPromiseRejections

test: add missing cases for unhandled events

---

lib/smart-app.js
package-lock.json
package.json

The HTTP signature validation library used by the SDK runs into issues with systems that re-write the request url, such as nginx and the AWS API gateway.  This issue with the library provides more information:
https://github.com/joyent/node-http-signature/issues/87
This PR also properly moves the snyk package to be a dev dependency, to reduce package since.

fix: Handle re-written URLs in HTTP signature validation

---

README.md
docs/classes/_pages_boolean_setting_d_.booleansetting.md
docs/classes/_pages_device_setting_d_.devicesetting.md
docs/index.md

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the **[CONTRIBUTING](/CONTRIBUTING.md)** document
- [ x] My code follows the code style of this project (hint: install an [xo editor plugin](https://github.com/xojs/xo#editor-plugins))
- [ x] Any required documentation has been added
- [ x] I have added tests to cover my changes

Documentation cleanup

---

docs/classes/_smart_app_d_.smartapp.md
docs/index.md
lib/smart-app.d.ts
lib/smart-app.js

Added a default handler for scheduled events that will be called whenever there isn't a matching handler for the schedule name. This feature is useful for cases where the name is used to convey information, such as the ID of an entity.

feat: added default scheduled event handler

---

docs/classes/_pages_decimal_setting_d_.decimalsetting.md
docs/classes/_pages_number_setting_d_.numbersetting.md
lib/pages/decimal-setting.d.ts
lib/pages/decimal-setting.js
lib/pages/number-setting.d.ts
lib/pages/number-setting.js

Updated the decimal and number settings to support translations of the `postMessage` field via locale files. Previously translation was not supported. Only literal values could be set with `postMessage`.
Also fixed a bug in the decimal setting where the i18n key was displayed but not translated,  if `postMessage` was not set.

feat: added i18n translation to postMessage fields

---

lib/smart-app.js
test/unit/smartapp-context-spec.js

Fixed a bug where the INSTALLED lifecycle event was overwriting any state items stored in the installed app context during the initial page flow.

fix: bug where context state was overwritten at install

---

lib/util/smart-app-context.js
package-lock.json
package.json
test/unit/smartapp-context-spec.js
test/utilities/context-store.js

Fix name errors in removeItem and removeAllItems context method.

fix: bugfix to context store remove item methods

---

.github/workflows/ci-cd.yaml
.npmignore
package-lock.json
package.json

Update package version of core SDK, axios, jest, and xo.

fix: update core sdk axios, jest, and xo
